global:
  scrape_interval: 5s


scrape_configs:
  - job_name: prometheus-aggregation
    honor_labels: true
    metrics_path: /federate
    params:
      match[]:
        - '{job=~".+"}'
    static_configs:
      - targets: 
        - prometheus-clark-sshtunnel:9090
        - prometheus-poweredge:9090
