{
 "title": "Cleezy",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Responses",
   "type": "timeseries",
   "description": "Excluding calls to /metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_code_total{path!=\"/metrics\"}",
     "legendFormat": "{{code}} {{path}}"
    }
   ]
  },
  {
   "title": "SQLite latency by query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "query_time_sum / query_time_count",
     "legendFormat": "{{query_type}}"
    }
   ]
  },
  {
   "title": "Container Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"cleezy\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}