{
 "title": "Paper Printing",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "SNMP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "snmp_request_duration_sum/snmp_request_duration_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ink Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "snmp_metric{name=\"ink_percent\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    { "expr": "snmp_error", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# of Pages Printed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "snmp_metric{name=\"page_count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Print Jobs Recieved",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(print_jobs_recieved_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}