{
 "title": "SCE Infra",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "time() - container_start_time_seconds{image=~\"clark.*|nginx|mongo\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Metric Health",
   "type": "timeseries",
   "description": "1 means up, 0 means down",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Container Last Seen (Clark Only)",
   "type": "timeseries",
   "description": "We use cadvisor with clark, thats why we have this metric",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "time() - container_last_seen{image=~\"clark.*|nginx|mongo\"}",
     "legendFormat": "{{image}}"
    }
   ]
  }
 ]
}