{
 "title": "SCE TV",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "bargauge",
   "description": "Number of requests received for each endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_request_count_total", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "Container Uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"sce-tv\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Data Downloaded",
   "type": "timeseries",
   "description": "Total video data downloaded in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "data_downloaded_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "API data rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "data_downloaded_total{job=\"sce-tv\"} * 8 / download_time_sum",
     "legendFormat": "bits/sec"
    }
   ]
  },
  {
   "title": "Download Time",
   "type": "timeseries",
   "description": "Total time spent downloading videos in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "download_time_sum", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Cache Hit/Miss",
   "type": "timeseries",
   "description": "Success/Failure in reading from cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "cache_hit_count_total", "legendFormat": "cache_hit_count" },
    { "expr": "cache_miss_count_total", "legendFormat": "cache_miss_count" }
   ]
  },
  {
   "title": "Total Videos Downloaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "video_download_count_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Cache Size Bytes",
   "type": "timeseries",
   "description": "Current cache size in bytes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "cache_size_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Total YouTube Videos Played",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "video_count_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "description": "Total entries in cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "cache_size{job=\"sce-tv\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}