{
 "title": "SCEta",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Cache Updated Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "cache_update_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Response Codes",
   "type": "timeseries",
   "description": "excluding /metrics",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "http_code_total{job=\"sceta-server\", path!=\"/metrics\"}",
     "legendFormat": "{{code}} {{path}}"
    }
   ]
  },
  {
   "title": "Cache Age",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "time() - cache_last_updated", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "511 API Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "api_response_codes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "511 API Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "api_latency_sum / api_latency_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}