{
 "title": "SSH Tunnel Health",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Time since last health check",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - last_health_check_request",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Time since SSH tunnel reopened",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - ssh_tunnel_last_opened",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Container Health ",
   "type": "timeseries",
   "description": "1 means up, 0 means down",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "up{job=~\"led-sign|delen|sce-printer\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "up{instance=\"prometheus-clark-sshtunnel:9090\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Container Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=~\"led-sign|delen|sce-printer\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}