# filepath: /Users/vineet/Projects/sce_system_status/prom/Dockerfile.scraper
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip3 install -r requirements.txt

COPY flags.py .
COPY scraper.py .
COPY templates/ ./templates/

CMD ["python3", "scraper.py", "--json", "json.json"]