version: '2'

services:
  coin-api:
    container_name: coin-api
    build:
      context: .
      dockerfile: ./dockerfile
    restart: 'on-failure'  
    ports:
      - "5000:5000"
  prometheus:
    image: prom/prometheus:latest
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  scraper:
    container_name: scraper
    build:
      context: .
      dockerfile: ./dockerfile.scraper
    volumes:
      - ./output:/app/output
      - ./templates:/app/templates
      - ./json.json:/app/json.json
    ports:
      - "8000:8000"
    restart: 'on-failure'
    command: python3 scraper.py --json json.json

  nginx:
    image: nginx:1.25.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
